[package]
name = "azux_sfml"
version = "0.1.0"
edition = "2021"
authors = ["AzuxirenLeadGuy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
sfml = "0.20.0"
